name: The Internet Selenium Python
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull and run Docker container
        run: |
          docker run -d -p 7080:5000 gprestes/the-internet

      - name: Run pytest
        run: |
          python main.py

      - name: Stop and remove Docker container
        run: |
          docker stop $(docker ps -q -f name=the-internet)
          docker rm $(docker ps -q -f name=the-internet)


